# Generated by Django 5.0.2 on 2024-02-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='coordinate',
            field=models.CharField(default='(0.0, 0.0)', max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='country_code',
            field=models.CharField(default='US', max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='pressure',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
