# Generated by Django 5.0.2 on 2024-02-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_weather_wind_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.CharField(),
        ),
    ]
